#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Migrate down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# set the theme's config file
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set a polybar on every monitor
index=0
IFS=$'\n' monitors=( $(polybar -m | sed s/:.*//) )
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  export WSINDEX=$index MONITOR=${monitors[$index]} WIDTH=$width OFFSETX=$x OFFSETY=$y
  polybar -c $SCRIPTPATH/polybar-config.ini leftwm &> /dev/null &
  index=$((index+1))
done
