#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Migrate down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# set the theme's config file
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set a polybar on every monitor that is connected.
index=0
IFS=$'\n' monitors=( $(polybar -m | sed s/:.*//) )
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width
do
  export WSINDEX=$index
  export MONITOR=${monitors[$index]}
  export BAR_WIDTH=$width
  polybar -c $SCRIPTPATH/polybar-config.ini leftwm 2> ~/.polybar-$index-errors.log &
  index=$((index+1))
done

# Check for monitor configuration
autorandr --change

# The arguments to xwallpaper are order dependent
xwallpaper --output eDP-1 --stretch ~/Pictures/Wallpapers/jwst-1.png
# If another monitor is connected.
xwallpaper --output HDMI-1 --stretch ~/Pictures/Wallpapers/jwst-3.png

xscreensaver --no-splash &
xsetroot -cursor_name right_ptr &
